import { Octokit } from '@octokit/rest';
import { logger } from '../logger/logger';
import { PullRequestAutomation } from '../models/PullRequestAutomation';
import { githubEvents } from './githubEvents';
import { GitHubPR } from './githubTypes';

// Initialize Octokit lazily to allow testing and env var loading
const getOctokit = () => {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    logger.warn('GITHUB_TOKEN is missing from environment variables');
  }
  return new Octokit({ auth: token });
};

export const githubService = {
  async triggerSafeAutomation(incidentId: string): Promise<GitHubPR> {
    const owner = process.env.GITHUB_OWNER;
    const repo = process.env.GITHUB_REPO;
    const defaultBranch = process.env.GITHUB_DEFAULT_BRANCH || 'main';

    if (!owner || !repo) {
      throw new Error('GITHUB_OWNER or GITHUB_REPO is missing from environment variables');
    }

    const octokit = getOctokit();
    const branchName = `fix/incident-${incidentId}-${Date.now()}`;
    const testFilePath = 'test.json';

    logger.info(`Starting safe GitHub automation for incident: ${incidentId}`);

    try {
      // 1. Get base branch reference
      const { data: refData } = await octokit.rest.git.getRef({
        owner,
        repo,
        ref: `heads/${defaultBranch}`,
      });

      // 2. Create new branch
      logger.info(`Creating branch ${branchName}...`);
      await octokit.rest.git.createRef({
        owner,
        repo,
        ref: `refs/heads/${branchName}`,
        sha: refData.object.sha,
      });

      // 3. Fetch existing test.json if it exists (need its SHA to update it)
      let fileSha: string | undefined;
      try {
        const { data: fileData } = await octokit.rest.repos.getContent({
          owner,
          repo,
          path: testFilePath,
          ref: branchName,
        });
        if (!Array.isArray(fileData) && fileData.type === 'file') {
          fileSha = fileData.sha;
        }
      } catch (err: any) {
        if (err.status !== 404) {
          throw err;
        }
      }

      // 4. Update or create the test file securely (only safe files for MVP)
      logger.info(`Modifying safe file ${testFilePath}...`);
      const fileContent = JSON.stringify({
        generatedBy: 'CatchMe AI',
        incidentId,
        timestamp: new Date().toISOString(),
        note: 'Safe test commit for MVP',
      }, null, 2);

      await octokit.rest.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: testFilePath,
        message: `[CatchMe AI] Safe test modification for incident ${incidentId}`,
        content: Buffer.from(fileContent).toString('base64'),
        branch: branchName,
        sha: fileSha,
      });

      // 5. Create Draft Pull Request
      logger.info(`Opening draft Pull Request for branch ${branchName}...`);
      const { data: prData } = await octokit.rest.pulls.create({
        owner,
        repo,
        title: `[CatchMe AI] Suggested Fix for Incident #${incidentId}`,
        head: branchName,
        base: defaultBranch,
        body: `## CatchMe AI Automated Pull Request\n\nThis is an automated **draft** PR generated by the CatchMe AI automation system for incident **#${incidentId}**.\n\n### Changes\n- Safely updated \`${testFilePath}\` to verify GitHub integration.\n\n_Note: This is a safe MVP implementation. No production files were modified._`,
        draft: true,
      });

      // 6. Save PR Metadata
      const prRecord = await PullRequestAutomation.create({
        incidentId,
        prNumber: prData.number,
        branchName,
        prUrl: prData.html_url,
        status: 'draft',
      });

      const result: GitHubPR = {
        id: prRecord._id.toString(),
        incidentId,
        prNumber: prRecord.prNumber,
        branchName: prRecord.branchName,
        prUrl: prRecord.prUrl,
        status: prRecord.status,
      };

      // 7. Broadcast via WebSocket
      githubEvents.emitPROpened(result);
      logger.info(`GitHub automation completed successfully for PR #${prData.number}`);

      return result;
    } catch (error: any) {
      logger.error(`GitHub automation failed: ${error.message}`);
      throw error;
    }
  },

  async getPullRequests(): Promise<GitHubPR[]> {
    const prs = await PullRequestAutomation.find().sort({ createdAt: -1 }).limit(50);
    return prs.map((pr) => ({
      id: pr._id.toString(),
      incidentId: pr.incidentId,
      prNumber: pr.prNumber,
      branchName: pr.branchName,
      prUrl: pr.prUrl,
      status: pr.status as any,
      createdAt: pr.createdAt.toISOString(),
      updatedAt: pr.updatedAt.toISOString(),
    }));
  },

  async getPullRequest(id: string): Promise<GitHubPR | null> {
    const pr = await PullRequestAutomation.findById(id);
    if (!pr) return null;
    return {
      id: pr._id.toString(),
      incidentId: pr.incidentId,
      prNumber: pr.prNumber,
      branchName: pr.branchName,
      prUrl: pr.prUrl,
      status: pr.status as any,
      createdAt: pr.createdAt.toISOString(),
      updatedAt: pr.updatedAt.toISOString(),
    };
  },
};
