import React from 'react';
import { Navbar } from '@/components/landing/Navbar';
import { Footer } from '@/components/landing/Footer';

export const metadata = {
  title: 'Privacy Policy | CatchMe AI',
  description: 'CatchMe AI Privacy Policy',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-brand-900 text-white selection:bg-brand-blue/30 overflow-x-hidden flex flex-col">
      <Navbar />
      <main className="flex-grow pt-32 pb-24 px-6 md:px-12 max-w-[800px] mx-auto w-full">
        <h1 className="text-4xl md:text-5xl font-black mb-4">Privacy Policy</h1>
        <p className="text-gray-400 mb-12">Effective Date: {new Date().toLocaleDateString()}</p>
        
        <div className="prose prose-invert prose-lg max-w-none space-y-8">
          <p className="text-gray-300 leading-relaxed font-medium">
            CatchMe AI respects your privacy and is committed to protecting personal and organizational information.
          </p>

          <div>
            <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">Information We Collect</h2>
            <ul className="list-disc pl-6 space-y-2 text-gray-300">
              <li>Account information</li>
              <li>Email addresses</li>
              <li>Authentication information</li>
              <li>Connected repository metadata</li>
              <li>Usage analytics</li>
              <li>Incident data generated by the platform</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">How We Use Information</h2>
            <ul className="list-disc pl-6 space-y-2 text-gray-300">
              <li>Provide platform functionality</li>
              <li>Improve service quality</li>
              <li>Detect operational issues</li>
              <li>Enhance security</li>
              <li>Communicate product updates</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">GitHub Integrations</h2>
            <div className="space-y-4 text-gray-300">
              <p>CatchMe AI only accesses repositories and resources explicitly authorized by users.</p>
              <p>We do not claim ownership of any repository, codebase, or organizational data connected through integrations.</p>
            </div>
          </div>

          <div>
            <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">Data Security</h2>
            <p className="text-gray-300 leading-relaxed">
              We implement encryption, access controls, monitoring systems, and industry-standard safeguards to protect user information.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">User Rights</h2>
            <p className="text-gray-300 leading-relaxed">
              Users may request access, correction, deletion, or export of their personal data.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
